350 fix account conf message
zero-filtre/zerofiltre-blog pull request #45
Opened 2022-10-03 06:59 UTC by EricMbouwe

2022-10-03 07:43 UTC, imphilippesimo commented on src/app/user/account-confirmation-page/account-confirmation-page.component.html
> +                😌.</span>
<span>Cependant, vous pouvez déjà rediger de nouveaux articles et confirmer votre compte plus tard 😉 </span>

2022-10-03 07:44 UTC, imphilippesimo commented on src/app/user/account-confirmation-page/account-confirmation-page.component.html
> +                😌.</span>
C'est bel et bien un lien qui doit retourner vers la page de listing des articles ? Sinon peux-tu l'ajouter ?

2022-10-03 07:45 UTC, imphilippesimo requested changes
Voir  les commentaires ci-dessus

2022-10-03 07:47 UTC, imphilippesimo commented on src/app/user/account-confirmation-page/account-confirmation-page.component.html
> +                😌.</span>
Il faut avoir le réflexe https://bonpatron.com/ chaque que l'on doit proposer du texte au user (Articles, boutons ...), les erreurs de grammaire et d'ortographe sont très discrédibilisantes.

2022-10-03 21:45 UTC, imphilippesimo requested changes

2022-10-03 21:45 UTC, imphilippesimo commented on src/app/user/account-confirmation-page/account-confirmation-page.component.html
> +            <span>Cependant, vous pouvez déjà rédiger de nouveaux articles et confirmer votre compte plus tard dépuis
depuis

2022-10-04 13:25 UTC, geek3000 approved these changes

2022-10-05 06:07 UTC, imphilippesimo approved these changes

2022-10-05 06:12 UTC, merged